# Generated by Django 4.2.7 on 2023-11-15 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0002_post_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(default="Write here"),
        ),
    ]
