# Generated by Django 4.2.7 on 2023-11-15 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0003_post_published_date_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
