# Generated by Django 4.2.7 on 2023-11-18 13:11

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0005_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=django_bleach.models.BleachField(blank=True, null=True),
        ),
    ]
