# Generated by Django 4.2.7 on 2023-12-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0009_product_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="paymentDate",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
