# Generated by Django 4.2.7 on 2023-11-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(default="Empty"),
        ),
    ]
