# Generated by Django 4.2.7 on 2023-12-11 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("theblog", "0017_remove_follow_following_follow_followed_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="follow",
            name="followed_users",
            field=models.ManyToManyField(
                default=[], related_name="followers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
