# Generated by Django 4.2.7 on 2023-12-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("theblog", "0021_alter_profile_following"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_posted",
            field=models.IntegerField(default=0),
        ),
    ]
